import { ProjectCategory, ProjectData } from './types';

const BASE_PATH = (import.meta.env.BASE_URL || '/').replace(/\/$/, '');
const asset = (pathname: string) => `${BASE_PATH}${pathname}`;

const storageBinsGallery = Array.from({ length: 9 }, (_, index) =>
  asset(`/assets/amazon/storage-bins/gallery-${String(index + 1).padStart(2, '0')}.png`),
);

const storageBins2Gallery = Array.from({ length: 9 }, (_, index) =>
  asset(`/assets/amazon/storage-bins-2/gallery-${String(index + 1).padStart(2, '0')}.png`),
);

const dogCollar2Detail = Array.from({ length: 7 }, (_, index) =>
  asset(`/assets/amazon/dog-collar-2/detail-${String(index + 1).padStart(2, '0')}.jpg`),
);

const dogCollarGallery = Array.from({ length: 8 }, (_, index) =>
  asset(`/assets/amazon/dog-collar/gallery-${String(index + 1).padStart(2, '0')}.jpg`),
);

const dogCollar2Gallery = [
  asset('/assets/amazon/dog-collar-2/gallery-01.png'),
  ...Array.from({ length: 8 }, (_, index) =>
    asset(`/assets/amazon/dog-collar-2/gallery-${String(index + 2).padStart(2, '0')}.jpg`),
  ),
];

export const PROJECTS: Record<ProjectCategory, ProjectData> = {
  [ProjectCategory.GRAPHIC]: {
    id: 'graphic-01',
    category: ProjectCategory.GRAPHIC,
    title: 'Pattern Design Collection',
    description: 'Three themed pattern projects presented as continuous long-form boards.',
    client: 'Self-Initiated Pattern Project',
    heroImage: asset('/assets/graphic/realm-of-wind-chasers-cover.png'),
    images: [
      asset('/assets/graphic/feline-blessing-cover.png'),
      asset('/assets/graphic/realm-of-wind-chasers-cover.png'),
      asset('/assets/graphic/tidal-oath-cover.png'),
    ],
    skills: [
      { name: 'Pattern System', value: 96 },
      { name: 'Motif Development', value: 94 },
      { name: 'Color Direction', value: 92 },
      { name: 'Surface Rhythm', value: 90 },
      { name: 'Application Design', value: 95 },
    ],
    tools: ['Photoshop', 'Illustrator', 'Procreate'],
    challenge: 'Translate three motif concepts into pattern-led boards that feel decorative, coherent, and easy to read online.',
    solution: 'Each project is shown as a direct long-scroll pattern board, pairing motif development with scarf-style application and a clearer viewing rhythm.',
    modules: [
      {
        id: 'feline-blessing',
        title: 'The Feline Blessing',
        subtitle: 'Chapter 01 / Feline Motif Pattern',
        display: 'long-scroll',
        boardFrame: 'plain',
        cover: asset('/assets/graphic/feline-blessing-cover.png'),
        sections: [
          {
            id: 'feline-blessing-board',
            title: 'Pattern Board',
            images: [asset('/assets/graphic/feline-blessing-long.png')],
          },
        ],
      },
      {
        id: 'realm-of-wind-chasers',
        title: 'The Realm of Wind-Chasers',
        subtitle: 'Chapter 02 / Scenic Pattern Collection',
        display: 'long-scroll',
        boardFrame: 'plain',
        cover: asset('/assets/graphic/realm-of-wind-chasers-cover.png'),
        sections: [
          {
            id: 'realm-of-wind-chasers-board',
            title: 'Pattern Board',
            images: [asset('/assets/graphic/realm-of-wind-chasers-long.png')],
          },
        ],
      },
      {
        id: 'tidal-oath',
        title: 'Tidal Oath',
        subtitle: 'Chapter 03 / Marine Motif Pattern',
        display: 'long-scroll',
        boardFrame: 'plain',
        cover: asset('/assets/graphic/tidal-oath-cover.png'),
        sections: [
          {
            id: 'tidal-oath-board',
            title: 'Pattern Board',
            images: [asset('/assets/graphic/tidal-oath-long.png')],
          },
        ],
      },
    ],
  },
  [ProjectCategory.FULL_BRANDING]: {
    id: 'branding-01',
    category: ProjectCategory.FULL_BRANDING,
    title: 'Brand Identity Case Study',
    description: 'A complete coffee brand system presented as one continuous editorial board.',
    client: 'Self-Initiated Coffee Brand',
    heroImage: asset('/assets/full-branding/mao-dot-cover.png'),
    images: [asset('/assets/full-branding/mao-dot-long.png')],
    skills: [
      { name: 'Brand System', value: 95 },
      { name: 'Art Direction', value: 93 },
      { name: 'Packaging Sense', value: 88 },
      { name: 'Editorial Layout', value: 91 },
    ],
    tools: ['Illustrator', 'Photoshop', 'InDesign'],
    challenge: 'Present one brand world online without breaking the identity system into disconnected slides or isolated mockups.',
    solution: 'MAO DOT is shown as a single long-scroll brand board so the logo, packaging, and rollout materials read as one cohesive case study.',
    modules: [
      {
        id: 'mao-dot',
        title: 'MAO DOT',
        subtitle: 'Coffee Brand Identity / Long-form case study',
        display: 'long-scroll',
        cover: asset('/assets/full-branding/mao-dot-cover.png'),
        sections: [
          {
            id: 'mao-dot-main',
            title: 'Brand Identity Board',
            description: 'Updated PNG export used directly for a sharper long-scroll brand presentation.',
            images: [asset('/assets/full-branding/mao-dot-long.png')],
          },
        ],
      },
    ],
  },
  [ProjectCategory.UI]: {
    id: 'ui-01',
    category: ProjectCategory.UI,
    title: 'Mobile UI Case Studies',
    description: 'Three app concepts displayed as an interactive mobile exhibition board.',
    client: 'Concept Product Projects',
    heroImage: asset('/assets/ui/scarf-app-overview.png'),
    images: [
      asset('/assets/ui/scarf-app-overview.png'),
      asset('/assets/ui/scarf-home-screen.png'),
      asset('/assets/ui/scarf-signup-screen.png'),
      asset('/assets/ui/scarf-style-analytics.png'),
      asset('/assets/ui/scarf-ai-assistant.png'),
      asset('/assets/ui/scarf-checkout-ui.png'),
      asset('/assets/ui/scarf-order-status.png'),
      asset('/assets/ui/scarf-resource-23.png'),
      asset('/assets/ui/scarf-resource-24.png'),
      asset('/assets/ui/pet-home-screen.png'),
      asset('/assets/ui/pet-discovery-screen.png'),
      asset('/assets/ui/pet-resource-5.png'),
      asset('/assets/ui/pet-resource-6.png'),
      asset('/assets/ui/pet-resource-7.png'),
      asset('/assets/ui/pet-resource-8.png'),
      asset('/assets/ui/pet-resource-9.png'),
      asset('/assets/ui/pet-resource-10.png'),
      asset('/assets/ui/pet-health-screen.png'),
      asset('/assets/ui/pet-community-screen.png'),
      asset('/assets/ui/milktea-splash-screen.png'),
      asset('/assets/ui/milktea-menu-screen.png'),
      asset('/assets/ui/milktea-customization-screen.png'),
      asset('/assets/ui/milktea-rewards-screen.png'),
      asset('/assets/ui/milktea-home-long.png'),
      asset('/assets/ui/milktea-resource-15.png'),
      asset('/assets/ui/milktea-resource-16.png'),
      asset('/assets/ui/milktea-resource-17.png'),
      asset('/assets/ui/milktea-resource-18.png'),
      asset('/assets/ui/milktea-resource-21.png'),
    ],
    skills: [
      { name: 'UX Flow', value: 92 },
      { name: 'UI System', value: 94 },
      { name: 'Interaction', value: 90 },
      { name: 'Visual Polish', value: 93 },
    ],
    tools: ['Figma', 'Photoshop', 'Illustrator'],
    challenge: 'Present multiple app concepts in one module without looking fragmented, while keeping each screen easy to scan and compare.',
    solution: 'Screens were arranged in a clear feed-like sequence from core entry points to key task flows, mirroring a concise ZCOOL case-study reading pattern.',
    modules: [
      {
        id: 'scarf-app',
        title: 'Scarf App',
        subtitle: 'Fashion utility + AI styling flow',
        display: 'ui',
        cover: asset('/assets/ui/scarf-home-screen.png'),
        coverColor: '#2A4C7A',
        images: [
          asset('/assets/ui/scarf-signup-screen.png'),
          asset('/assets/ui/scarf-board-1.png'),
          asset('/assets/ui/scarf-board-2.png'),
          asset('/assets/ui/scarf-style-analytics.png'),
          asset('/assets/ui/scarf-ai-assistant.png'),
          asset('/assets/ui/scarf-checkout-ui.png'),
          asset('/assets/ui/scarf-order-status.png'),
          asset('/assets/ui/scarf-resource-23.png'),
          asset('/assets/ui/scarf-resource-24.png'),
        ],
      },
      {
        id: 'pet-app',
        title: 'Pet App',
        subtitle: 'Care, discovery, and activity module',
        display: 'ui',
        cover: asset('/assets/ui/pet-home-screen.png'),
        coverColor: '#2F6A58',
        images: [
          asset('/assets/ui/pet-home-screen.png'),
          asset('/assets/ui/pet-discovery-screen.png'),
          asset('/assets/ui/pet-resource-5.png'),
          asset('/assets/ui/pet-resource-6.png'),
          asset('/assets/ui/pet-resource-7.png'),
          asset('/assets/ui/pet-resource-8.png'),
          asset('/assets/ui/pet-resource-9.png'),
          asset('/assets/ui/pet-resource-10.png'),
          asset('/assets/ui/pet-health-screen.png'),
          asset('/assets/ui/pet-community-screen.png'),
        ],
      },
      {
        id: 'milk-tea-app',
        title: 'Milk Tea App',
        subtitle: 'Ordering + rewards + customization flow',
        display: 'ui',
        cover: asset('/assets/ui/milktea-menu-screen.png'),
        coverColor: '#7B5230',
        images: [
          asset('/assets/ui/milktea-splash-screen.png'),
          asset('/assets/ui/milktea-menu-screen.png'),
          asset('/assets/ui/milktea-customization-screen.png'),
          asset('/assets/ui/milktea-rewards-screen.png'),
          asset('/assets/ui/milktea-home-long.png'),
          asset('/assets/ui/milktea-resource-15.png'),
          asset('/assets/ui/milktea-resource-16.png'),
          asset('/assets/ui/milktea-resource-17.png'),
          asset('/assets/ui/milktea-resource-18.png'),
          asset('/assets/ui/milktea-resource-21.png'),
        ],
      },
    ],
  },
  [ProjectCategory.AMAZON]: {
    id: 'amz-01',
    category: ProjectCategory.AMAZON,
    title: 'Amazon Listing Design Collection',
    description: 'Main images and detail pages presented inside an Amazon-style product viewing frame.',
    client: 'E-commerce Product Clients',
    heroImage: asset('/assets/amazon/storage-bins-2/gallery-01.png'),
    images: [
      asset('/assets/amazon/storage-bins/gallery-01.png'),
      asset('/assets/amazon/storage-bins-2/gallery-01.png'),
      asset('/assets/amazon/dog-collar-2/gallery-01.png'),
    ],
    skills: [
      { name: 'Marketplace Visuals', value: 95 },
      { name: 'Conversion Layout', value: 92 },
      { name: 'Info Hierarchy', value: 90 },
      { name: 'Image Retouching', value: 89 },
    ],
    tools: ['Photoshop', 'Illustrator', 'Figma'],
    challenge: 'Show Amazon listing work inside the portfolio as a believable storefront experience instead of a loose image dump.',
    solution: 'Each listing is rebuilt into a familiar Amazon-style frame with thumbnail navigation, product-copy scaffolding, and the original A+ detail boards flowing underneath.',
    modules: [
      {
        id: 'dog-collar',
        title: 'Smart Collar',
        subtitle: 'Anti-bark collar / 8-image gallery + detail page',
        display: 'amazon',
        cover: asset('/assets/amazon/dog-collar/gallery-01.jpg'),
        amazon: {
          productTitle: 'AI Smart Anti-Bark Collar',
          price: '$239.00',
          rating: '4.6',
          reviewCount: '842',
          badge: 'Smart Collar Mock',
          availability: 'Premium device in stock',
          shipping: 'Direct fulfillment available',
          breadcrumb: ['Pet Supplies', 'Dogs', 'Collars, Harnesses & Leashes'],
          highlights: ['AI Voiceprint', 'Smart Collar', 'A+ Detail'],
          bullets: [
            'Smart anti-bark collar with AI voiceprint positioning and anti-interference messaging.',
            'Main images now follow the updated numbered sequence from the source folder instead of the old stitched long board.',
            'The detail page below continues the smart-collar story with modes, waterproofing, and sizing information.',
          ],
          galleryImages: dogCollarGallery,
          detailImages: [asset('/assets/amazon/dog-collar/detail-long.png')],
        },
      },
      {
        id: 'dog-collar-2',
        title: '2-in-1 Smart Collar',
        subtitle: 'Training collar / 9-image gallery + 7 detail panels',
        display: 'amazon',
        cover: asset('/assets/amazon/dog-collar-2/gallery-01.png'),
        amazon: {
          productTitle: '2-in-1 Smart Training Collar',
          price: '$289.00',
          rating: '4.8',
          reviewCount: '1,126',
          badge: 'Training System Mock',
          availability: 'High-ticket training device',
          shipping: 'Professional training bundle',
          breadcrumb: ['Pet Supplies', 'Dogs', 'Training & Walking', 'Collars'],
          highlights: ['2-in-1 Training', 'Smart Collar', 'Remote System'],
          bullets: [
            '2-in-1 smart training collar system that pairs a remote transmitter with the collar receiver.',
            'Main images follow the refreshed numbered sequence, with the PNG hero frame intentionally kept first.',
            'Detail panels explain the training features, dual-channel setup, and premium device positioning.',
          ],
          galleryImages: dogCollar2Gallery,
          detailImages: dogCollar2Detail,
        },
      },
      {
        id: 'storage-bins',
        title: 'Storage Bins',
        subtitle: 'Home storage / square gallery + long A+ board',
        display: 'amazon',
        cover: asset('/assets/amazon/storage-bins/gallery-01.png'),
        amazon: {
          productTitle: 'Fabric Storage Bins Listing Design',
          price: '$29.99',
          rating: '4.7',
          reviewCount: '2,084',
          badge: 'Amazon PDP Mock',
          availability: 'In Stock',
          shipping: 'Warehouse restock available',
          breadcrumb: ['Home & Kitchen', 'Storage & Organization', 'Bins & Containers'],
          highlights: ['9 Main Images', 'Long Detail Page', 'Home Category'],
          bullets: [
            'Primary images are kept in the standard Amazon square format for gallery viewing.',
            'The long-form detail image is placed below the fold to mirror an A+ content read.',
            'The composition balances lifestyle utility shots with labeled product benefits.',
          ],
          galleryImages: storageBinsGallery,
          detailImages: [asset('/assets/amazon/storage-bins/detail-long.png')],
        },
      },
      {
        id: 'storage-bins-2',
        title: 'Storage Bins Variant',
        subtitle: 'Alternate image set / long A+ board',
        display: 'amazon',
        cover: asset('/assets/amazon/storage-bins-2/gallery-01.png'),
        amazon: {
          productTitle: 'Storage Bin Listing Variant',
          price: '$32.99',
          rating: '4.8',
          reviewCount: '1,548',
          badge: 'Portfolio Mock',
          availability: 'Ready for listing update',
          shipping: 'Bundled shipping mock',
          breadcrumb: ['Home & Kitchen', 'Storage & Organization', 'Closet Accessories'],
          highlights: ['Variant Set', '9 Main Images', 'Long-form Detail'],
          bullets: [
            'A second listing direction with refreshed imagery and alternate feature emphasis.',
            'The simulated product page keeps the browsing logic close to an actual Amazon PDP.',
            'The long detail board remains fully visible in the same continuous scroll flow.',
          ],
          galleryImages: storageBins2Gallery,
          detailImages: [asset('/assets/amazon/storage-bins-2/detail-long.png')],
        },
      },
    ],
  },
  [ProjectCategory.ADDITIONAL]: {
    id: 'additional-01',
    category: ProjectCategory.ADDITIONAL,
    title: 'Selected Additional Works',
    description: 'Editorial boards, poster studies, and illustration-based side projects.',
    client: 'Independent Design Projects',
    heroImage: asset('/assets/additional/human-machine-relationship/poster-01.png'),
    images: [
      asset('/assets/additional/selected-works-2025/selected-works-long.png'),
      asset('/assets/additional/human-machine-relationship/poster-01.png'),
      asset('/assets/additional/human-machine-relationship/poster-02.png'),
      asset('/assets/additional/facai-illustration/board-01.jpeg'),
    ],
    skills: [
      { name: 'Poster Design', value: 94 },
      { name: 'Concept Framing', value: 92 },
      { name: 'Editorial Sequencing', value: 89 },
      { name: 'Visual Experiments', value: 96 },
    ],
    tools: ['Photoshop', 'Illustrator', 'InDesign'],
    challenge: 'Present side projects with very different formats without flattening them into one generic layout.',
    solution: 'Each work uses the presentation mode that suits it best: long-scroll for editorial boards, gallery view for posters, and a compact scroll sequence for Facai Illustration.',
    modules: [
      {
        id: 'selected-works-2025',
        title: 'Selected Works 2025',
        subtitle: 'Portfolio board / 2025 compilation',
        display: 'long-scroll',
        boardFrame: 'plain',
        loadingEffect: 'none',
        cover: asset('/assets/additional/selected-works-2025/selected-works-long.png'),
        sections: [
          {
            id: 'selected-works-board',
            title: 'Portfolio Board',
            description: 'Updated PNG export for a sharper direct-scroll presentation.',
            images: [asset('/assets/additional/selected-works-2025/selected-works-long.png')],
          },
        ],
      },
      {
        id: 'human-machine-relationship',
        title: 'Human–Machine Relationship',
        subtitle: 'Poster series / three-image gallery',
        display: 'gallery',
        loadingEffect: 'none',
        cover: asset('/assets/additional/human-machine-relationship/poster-01.png'),
        images: [
          asset('/assets/additional/human-machine-relationship/poster-01.png'),
          asset('/assets/additional/human-machine-relationship/poster-02.png'),
          asset('/assets/additional/human-machine-relationship/poster-03.png'),
        ],
      },
      {
        id: 'facai-illustration',
        title: 'Facai Illustration',
        subtitle: 'Character illustration / extension mockups',
        display: 'long-scroll',
        boardFrame: 'framed',
        loadingEffect: 'none',
        cover: asset('/assets/additional/facai-illustration/board-01.jpeg'),
        sections: [
          {
            id: 'facai-illustration-series',
            title: 'Project Sequence',
            description: 'Character visuals and product-style mockups presented as a compact scrollable case sequence.',
            images: [
              asset('/assets/additional/facai-illustration/board-01.jpeg'),
              asset('/assets/additional/facai-illustration/board-02.jpeg'),
              asset('/assets/additional/facai-illustration/board-03.jpeg'),
              asset('/assets/additional/facai-illustration/board-04.jpeg'),
              asset('/assets/additional/facai-illustration/board-05.jpeg'),
              asset('/assets/additional/facai-illustration/board-06.png'),
              asset('/assets/additional/facai-illustration/board-07.png'),
            ],
          },
        ],
      },
    ],
  },
};
